### ISSUE TITLE
Cannot be used behind the firewall

### ISSUE THREAD

**Issue by gbatalski** [arin-pang/nodejs-sonar-scanner#4]
Hi and thank you for this fork!

The idea behind the original project was the usage of a wrapped (embedded) cli. Now, with latest changes, i cannot download the cli jar because of fixed URLs which are not allowed from our CI server. Possibly the proxying  the binaries via additional env variables could be a solution. But in this case i don't understand the difference to [sonarqube-scanner](https://www.npmjs.com/package/sonarqube-scanner) plugin.

Regards, Gena

**Comment by arin-pang** [comment]
Hi, @gbatalski!
About your question, @Eddman contributed already. (#2) 

You need to proxy not only the binary file, but also [a Github tags API](https://api.github.com/repos/SonarSource/sonar-scanner-cli/tags).

Well... actually, this project just only provide downloading a released binary automatically.
In the others, I think [sonarqube-scanner](https://www.npmjs.com/package/sonarqube-scanner) is better 🤣

I just added the feature for my project 😅
